Repository Exist95/Front-interview, pull requests merged in 2023-02, with the labels that each got.

#39 [FEAT]: 로그인 여부에 따른 렌더링
  client/App.tsx
  client/model/authModel.ts
  client/router/AuthStack.tsx
  client/router/Routes.tsx
  client/router/Stack.tsx
  client/router/index.tsx
  client/store/form.ts
  client/store/login.ts
  client/types/auth.ts
  client/view/MyPage/index.tsx
  client/view/Note/index.tsx
  client/view/Questions/index.tsx
  client/view/Result/index.tsx
  client/view/SignUp/index.tsx
  client/view/components/Common/Header/index.tsx
  client/view/components/Common/Header/style.ts
  client/view/components/Common/NavigationButton/index.tsx
  client/view/components/Form/index.tsx
  client/vm/FormViewModel.ts
  client/vm/LoginViewModel.ts
Labels: FE

#40 [FEAT]: 접근 제한 페이지 테스트
  client/view/Result/index.tsx
Labels: FE

#41 [FEAT]: 회원탈퇴, 로그아웃, 랭킹 페이지 구현
  client/App.tsx
  client/app.json
  client/model/authModel.ts
  client/model/rankingModel.ts
  client/package-lock.json
  client/package.json
  client/provider/index.tsx
  client/router/Stack.tsx
  client/router/index.tsx
  client/store/darkMode.ts
  client/store/login.ts
  client/types/Users.ts
  client/util/navigation.tsx
  client/view/Login/index.tsx
  client/view/Login/style.ts
  client/view/MyPage/index.tsx
  client/view/MyPage/style.ts
  client/view/Ranking/RankingList/index.tsx
  client/view/Ranking/RankingList/style.ts
  client/view/Ranking/index.tsx
  client/view/Ranking/style.ts
  client/view/components/Common/NavigationButton/index.tsx
  client/vm/DarkModeViewModel.ts
  client/vm/FormViewModel.ts
  client/vm/LoginViewModel.ts
  client/vm/Modal.ts
Labels: FE

#42 [FEAT]: 애니메이션 추가
  client/router/Stack.tsx
  client/view/Main/index.tsx
  client/view/Main/style.ts
  client/view/MyPage/index.tsx
  client/view/components/Common/Header/style.ts
Labels: FE

#43 [FEAT]: questions 페이지 기능 구현
  client/App.tsx
  client/model/questionsModel.ts
  client/pages/Auth/NavigateLogin/index.tsx
  client/router/Stack.tsx
  client/router/index.tsx
  client/store/questions.ts
  client/types/Questions.ts
  client/types/result.ts
  client/view/Login/index.tsx
  client/view/MyPage/index.tsx
  client/view/Note/index.tsx
  client/view/Questions/index.tsx
  client/view/Questions/style.ts
  client/view/Result/index.tsx
  client/view/SignUp/index.tsx
  client/view/components/Common/Form/index.tsx
  client/view/components/Common/Form/style.ts
  client/view/components/Common/NavigateLogin/index.tsx
  client/view/components/Common/NavigateLogin/style.ts
  client/view/components/Common/NavigationButton/index.tsx
  client/vm/LoginViewModel.ts
  client/vm/QuestionsViewModel.ts
Labels: FE

#45 [FEAT]: 오답노트 구현
  client/model/questionsModel.ts
  client/package-lock.json
  client/types/result.ts
  client/view/MyPage/index.tsx
  client/view/Note/NoteList/style.ts
  client/view/Note/index.tsx
  client/view/Note/style.ts
  client/view/Result/index.tsx
  server/controllers/users-controller.js
Labels: FE, BE

#46 [FEAT]: 아이디 저장, 비밀번호 변경 View 구성
  client/router/index.tsx
  client/view/Login/index.tsx
  client/view/Login/style.ts
  client/view/Note/NoteList/index.tsx
  client/view/Note/NoteList/style.ts
  client/view/Note/index.tsx
  client/view/Note/style.ts
  client/view/Ranking/index.tsx
  client/view/Ranking/style.ts
  client/view/components/Common/Header/index.tsx
  server/controllers/users-controller.js
Labels: FE

#47 [FEAT]: 아이디 저장 기능 구현
  client/package-lock.json
  client/package.json
  client/store/login.ts
  client/view/Login/index.tsx
  client/view/Login/style.ts
  client/view/components/Common/Form/index.tsx
  client/vm/FormViewModel.ts
  client/vm/LoginViewModel.ts
  client/vm/WrongAnswerViewModel.ts
Labels: FE

#48 [FEAT]: 회원가입 유효성 검사, 비밀번호 변경 기능 구현
  client/model/passwordModel.ts
  client/pages/Password.tsx
  client/router/Stack.tsx
  client/store/form.ts
  client/store/password.ts
  client/types/password.ts
  client/view/Login/index.tsx
  client/view/Login/style.ts
  client/view/MyPage/index.tsx
  client/view/MyPage/style.ts
  client/view/Password/index.tsx
  client/view/Password/style.ts
  client/view/Result/index.tsx
  client/view/SignUp/index.tsx
  client/view/components/Common/Form/index.tsx
  client/view/components/Common/Form/style.ts
  client/view/components/Common/NavigationButton/index.tsx
  client/vm/FormViewModel.ts
  client/vm/PasswordViewModel.ts
Labels: FE

#49 [REFECTOR]: 서버 로그인 로직 수정
  client/router/Stack.tsx
  client/view/Login/index.tsx
  client/view/Login/style.ts
  client/view/MyPage/index.tsx
  client/view/MyPage/style.ts
  server/controllers/users-controller.js
Labels: BE

#50 [FEAT]: 소제목 랜덤 렌더링
  client/router/Stack.tsx
  client/view/Login/index.tsx
  client/view/Main/index.tsx
Labels: FE

#51 [CHORE]: dev => main
  client/model/passwordModel.ts
  client/model/questionsModel.ts
  client/package-lock.json
  client/package.json
  client/pages/Password.tsx
  client/router/Stack.tsx
  client/router/index.tsx
  client/store/form.ts
  client/store/login.ts
  client/store/password.ts
  client/types/password.ts
  client/types/result.ts
  client/view/Login/index.tsx
  client/view/Login/style.ts
  client/view/Main/index.tsx
  client/view/MyPage/index.tsx
  client/view/MyPage/style.ts
  client/view/Note/NoteList/index.tsx
  client/view/Note/NoteList/style.ts
  client/view/Note/index.tsx
  client/view/Note/style.ts
  client/view/Password/index.tsx
  client/view/Password/style.ts
  client/view/Ranking/index.tsx
  client/view/Ranking/style.ts
  client/view/Result/index.tsx
  client/view/SignUp/index.tsx
  client/view/components/Common/Form/index.tsx
  client/view/components/Common/Form/style.ts
  client/view/components/Common/Header/index.tsx
  client/view/components/Common/NavigationButton/index.tsx
  client/vm/FormViewModel.ts
  client/vm/LoginViewModel.ts
  client/vm/PasswordViewModel.ts
  client/vm/WrongAnswerViewModel.ts
  server/controllers/users-controller.js
Labels: FE
